// config
require.config({
    baseUrl: "./",
    // paths
    paths: {
        "angular": "lib/angular/angular.min",
        "angular-animate": "lib/angular/angular-animate.min",
        "angular-sanitize": "lib/angular/angular-sanitize.min",
        "angular-resource": "lib/angular/angular-resource.min",
        "angular-ui-router": "lib/angular-ui-router/angular-ui-router.min",
        "angular-css": "lib/angular-css/angular-css.min",
        "angular-translate-loader-static-files": "lib/angular-ui-router/angular-translate-loader-static-files.min",
        "angularAMD": "lib/angular-amd/angularAMD.min",
        "angular-idle": "lib/plugins/angular-idle/angular-idle",
        "ocLazyLoad": "lib/plugins/oclazyload/dist/ocLazyLoad",
        "ui-bootstrap-tpls": "lib/bootstrap/ui-bootstrap-tpls-1.1.2.min",
        "angular-translate": "lib/angular-translate/angular-translate.min",
        "jquery": "lib/jquery/jquery-2.1.1.min",
        "jquery-ui": "lib/plugins/jquery-ui/jquery-ui",
        "jsTree": "lib/plugins/jsTree/jstree.min",
        "ngJsTree": "lib/plugins/jsTree/ngJsTree.min",
        "bootstrap": "lib/bootstrap/bootstrap",
        "metisMenu": "lib/plugins/metisMenu/jquery.metisMenu",
        "slimscroll": "lib/plugins/slimscroll/jquery.slimscroll.min",
        "pace": "lib/plugins/pace/pace.min",
        "bootbox": "lib/bootbox/bootbox.min",
        "iCheck": "lib/plugins/iCheck/icheck.min",
        'iinput': "directive/iinput",
        "inspinia": "js/inspinia",
        "pageTitle": "directive/pageTitle",
        "sideNavigation": "directive/sideNavigation",
        "iboxTools": "directive/iboxTools",
        "popTools": "directive/popTools",
        "minimalizaSidebar": "directive/minimalizaSidebar",
        "vectorMap": "directive/vectorMap",
        "sparkline": "directive/sparkline",
        "icheck": "directive/icheck",
        "ionRangeSlider": "directive/ionRangeSlider",
        "dropZone": "directive/dropZone",
        "responsiveVideo": "directive/responsiveVideo",
        "chatSlimScroll": "directive/chatSlimScroll",
        "customValid": "directive/customValid",
        "fullScroll": "directive/fullScroll",
        "closeOffCanvas": "directive/closeOffCanvas",
        "clockPicker": "directive/clockPicker",
        // "landingScrollspy": "directive/landingScrollspy",
        "fitHeight": "directive/fitHeight",
        "iboxToolsFullScreen": "directive/iboxToolsFullScreen",
        "slimScroll": "directive/slimScroll",
        "truncate": "directive/truncate",
        "touchSpin": "directive/touchSpin",
        "markdownEditor": "directive/markdownEditor",
        "toggleAddon": "directive/toggleAddon",
        "radioBtn": "directive/radioBtn",
        "comboTree": "directive/comboTree",
        "comboModuleTree": "directive/comboModuleTree",
        "deptTree": "directive/deptTree",
        "deptPersonTree": "directive/deptPersonTree",
        "datatables.net": 'lib/plugins/angular-dataTables/jquery.dataTables',
        "datatables.net-buttons": "lib/plugins/dataTables/dataTables.buttons.min",
        "datatables.net-select": 'lib/plugins/dataTables/dataTables.select',
        'datatables.bootstrap': 'lib/plugins/dataTables/dataTables.bootstrap',
        "datatables": "lib/plugins/angular-dataTables/angular-datatables",
        "datatables.buttons": "lib/plugins/angular-dataTables/angular-datatables.buttons.min",
        "datatables.select": "lib/plugins/angular-dataTables/angular-datatables.select.min",
        //"datatables.buttons":"lib/plugins/angular-dataTables/angular-datatables.buttons.min"
        "cgNotify": "lib/plugins/angular-notify/angular-notify.min",
        "moment": "lib/plugins/moment/moment.min",
        "moment.zh-cn": "lib/plugins/moment/i18n/zh-cn",
        "parsley": "lib/plugins/parsley/parsley.min",
        "parseley.zh-cn": "lib/plugins/parsley/i18n/zh-cn",
        "pager": "directive/pager",
        "actionButton": "directive/actionButton",
        "daterangepicker": "lib/plugins/daterangepicker/daterangepicker",
        "angular-daterangepicker": "lib/plugins/daterangepicker/angular-daterangepicker",
        "angular-datetimepicker": "lib/plugins/datetimepicker/datetimepicker",
        "angular-datetimepicker-templates": "lib/plugins/datetimepicker/datetimepicker.templates",
        "angular-datepicker": "lib/plugins/angular-datepicker/angular-datepicker",
        "sidemenu": "directive/sidemenu",
        "topnavbar": "directive/topnavbar",
        "echarts": "lib/echarts/echarts.min",
        "loading-bar": "lib/loading-bar/loading-bar",
        "personTypeahead": "directive/personTypeahead",
        "accountTypeahead": "directive/accountTypeahead",
        "driverInput": "directive/driverInput",
        "plateInput": "directive/plateInput",
        "monthRangePicker":"directive/monthRangePicker",
        // AMap
        "AMap": "http://webapi.amap.com/maps?v=1.3&key=1b46ac543c8fb3c1a052dcbae57eb766&plugin=AMap.Geocoder",
        "ol": "lib/ol/ol",
        "om": "lib/ol/om",
        "imageUpload": "directive/imageUpload",
        "rzslider":"lib/plugins/angularjs-slider/rzslider",
        //Service
        "UtilService": "service/utilService",
        "MapService": "service/mapService",
        "ConfigService": "service/configService",
    },
    // shim
    shim: {
        // angular
        //"jquery-datatables":["jquery"],
        //"bootstrap-datatables":["jquery-datatables","bootstrap"],
        "angular": { exports: "angular", deps: ["jquery"] },
        "echarts": { exports: "echarts" },
        "angular-animate": ["angular"],
        "angular-sanitize": ["angular"],
        "angular-resource": ["angular"],
        "angular-ui-router": ["angular"],
        "angular-translate": ["angular"],
        "angular-translate-loader-static-files": ["angular-translate"],
        "angular-css": ["angular"],
        "angularAMD": ["angular"],
        "angular-idle": ["angular"],
        "ocLazyLoad": ["angular"],
        "ui-bootstrap-tpls": ["angular"],
        "loading-bar": { exports: "angular-loading-bar", deps: ["angular"] },
        "moment": ["jquery"],
        "moment.zh-cn": ["moment"],
        "daterangepicker": ["jquery", "moment"],
        "angular-daterangepicker": ["angular", "daterangepicker"],
        "angular-datepicker": { deps: ["angular", "moment"] },
        "angular-datetimepicker": ["jquery", "moment.zh-cn", "angular"],
        "angular-datetimepicker-templates": ["angular-datetimepicker"],
        "slimscroll": ["jquery"],
        "jquery-ui": ["jquery"],
        "jsTree": ["jquery"],
        "ngJsTree": ["jsTree"],
        "iCheck": ["jquery"],
        "pace": ["jquery"],
        "bootbox": { exports: "bootbox", deps: ["bootstrap"] },
        "cgNotify": { deps: ["jquery", "angular"] },
        "inspinia": ["jquery"],
        "bootstrap": ["jquery"],
        "metisMenu": ["jquery"],
        "pageTitle": ["angularAMD"],
        "sideNavigation": ["angularAMD", "metisMenu"],
        "iboxTool": ["angularAMD"],
        "minimalizaSidebar": ["angularAMD"],
        "vectorMap": ["angularAMD"],
        "sparkline": ["angularAMD"],
        "icheck": ["angular", "angularAMD"],
        "iinput": ["angular", "angularAMD"],
        "ionRangeSlider": ["angularAMD"],
        "dropZone": ["angularAMD"],
        "responsiveVideo": ["angularAMD"],
        "chatSlimScroll": ["angularAMD"],
        "customValid": ["angularAMD"],
        "fullScroll": ["angularAMD"],
        "comboTree": ["angularAMD"],
        "comboModuleTree": ["angularAMD"],
        "deptTree": ["angularAMD"],
        "deptPersonTree": ["angularAMD"],
        "personTypeahead": ["angularAMD"],
        "accountTypeahead": ["angularAMD"],
        "driverInput": ["angularAMD"],
        "plateInput": ["angularAMD"],
        "monthRangePicker": ["angularAMD"],
        "closeOffCanvas": ["angularAMD"],
        "clockPicker": ["angularAMD"],
        // "landingScrollspy": ["angularAMD"],
        "fitHeight": ["angularAMD"],
        "iboxToolsFullScreen": ["angularAMD"],
        "slimScroll": ["angularAMD", "jquery"],
        "truncate": ["angularAMD"],
        "touchSpin": ["angularAMD"],
        "markdownEditor": ["angularAMD"],
        "toggleAddon": ["angularAMD"],
        "datatables.net": ["jquery", "jquery-ui"],
        "datatables.net-select": ["datatables.net"],
        "datatables.bootstrap": ["datatables.net", "bootstrap"],
        "datatables": ["datatables.net", "angular", "datatables.bootstrap"],
        "datatables.net-buttons": ["datatables.net"],
        "datatables.buttons": ["datatables", "datatables.net-buttons"],
        "datatables.select": ["datatables", "datatables.net-select", "datatables.buttons"],
        //"datatables.buttons":["datatables"]
        "parsley": ["jquery"],
        "parseley.zh-cn": ["parsley"],
        "pager": ["angular"],
        "actionButton": ["angular"],
        "sidemenu": ["angular"],
        "topnavbar": ["angular"],
        // AMap
        "AMap": { exports: "AMap" },
        //UtilService
        "UtilService": ["angularAMD","ConfigService"],

        "MapService": ["angularAMD","UtilService"],

        rzslider: ["angularAMD"]
    },waitSeconds: 300
});
// bootstrap
define([
    "jquery",
    "angular",
    "angularAMD",
    "routes",
    "angular-css",
    "angular-sanitize",
    "angular-idle",
    "ocLazyLoad",
    "angular-ui-router",
    "ui-bootstrap-tpls",
    //"bootstrap-datatables",
    "angular-translate-loader-static-files",
    "bootstrap",
    "iCheck",
    "pace",
    "bootbox",
    "metisMenu",
    "pageTitle",
    "sideNavigation",
    "iboxTools",
    "popTools",
    "minimalizaSidebar",
    "vectorMap",
    "sparkline",
    "icheck",
    "iinput",
    "ionRangeSlider",
    "dropZone",
    "responsiveVideo",
    "chatSlimScroll",
    "customValid",
    "fullScroll",
    "comboTree",
    "comboModuleTree",
    "deptTree",
    "deptPersonTree",
    "closeOffCanvas",
    "clockPicker",
    // "landingScrollspy",
    "fitHeight",
    "iboxToolsFullScreen",
    "slimscroll",
    "truncate",
    "touchSpin",
    "markdownEditor",
    "toggleAddon",
    "parsley",
    "parseley.zh-cn",
    "jquery-ui",
    "datatables",
    "datatables.select",
    "cgNotify",
    "angular-daterangepicker",
    "angular-datetimepicker",
    "angular-datetimepicker-templates",
    "angular-datepicker",
    "pager",
    "actionButton",
    "personTypeahead",
    "accountTypeahead",
    "driverInput",
    "plateInput",
    "monthRangePicker",
    "sidemenu",
    "topnavbar",
    "loading-bar",
    "UtilService",
    "MapService",
    "rzslider",
    "imageUpload",
    "radioBtn"
],

    function ($, angular, angularAMD, registerRoutes) {
        var app = angular.module("inspinia", [
            "datatables",
            'datatables.buttons',
            'datatables.select',
            //'datatables.bootstrap',
            "ui.router",                    // Routing
            "angularCSS",
            "oc.lazyLoad",                  // ocLazyLoad
            "ui.bootstrap",                 // Ui Bootstrap
            "pascalprecht.translate",       // Angular Translate
            "ngIdle",                       // Idle timer
            "ngSanitize",                    // ngSanitize
            "cgNotify",
            "daterangepicker",
            "ui.bootstrap.datetimepicker",
            "datePicker",
            'chieffancypants.loadingBar',
            "rzModule"
        ]);
        app.config(function ($stateProvider, $urlRouterProvider, $ocLazyLoadProvider, IdleProvider) {
            // Configure Idle settings
            IdleProvider.idle(5); // in seconds
            IdleProvider.timeout(120); // in seconds
            $ocLazyLoadProvider.config({
                debug: true // Set to true if you want to see what and when is dynamically loaded
            });
        });
        app.config(["$stateProvider", "$urlRouterProvider", registerRoutes]);
        app.config(function ($translateProvider) {
            $translateProvider.useStaticFilesLoader({
                prefix: "/i18n/",
                suffix: ".json"
            });
            $translateProvider.preferredLanguage("zh");
        });

        app.run(function (DTDefaultOptions) {
            DTDefaultOptions.setOption('dom', '<<t>>');
            DTDefaultOptions.setOption('sPaginationType', 'full_numbers');
            DTDefaultOptions.setOption('aLengthMenu', [[1, 25, 50, -1], ["2条", "25条", "50条", "All"]]);
            DTDefaultOptions.setOption('pageLength', 20);
            DTDefaultOptions.setLanguageSource("i18n/datatables-zh.json");
        });
        //console.log('moment.locale');

        angularAMD.bootstrap(app);
    });
// Other libraries are loaded dynamically in the config.js file using the library ocLazyLoad